### ISSUE TITLE
No display the correct speed type for a volume

### ISSUE THREAD

**Issue by cbouisson-csgroup** [CS-SI/SafeScale#12]

**Comment by saimeCS** [comment]
Type of volume disk is display with human readable info (SSD, HHD or COLD) instead of numerical value.
Some providers only offer 2 types of volume and it is configured in client.go of each provider.
Moreover, a fall-back mechanism is set to 'downgrade' requested speed trying to find an possible speed according to the current provider and finally create a volume.
commit: d2605d35cdfcd80cfdc8ccba3f53a95f2a1641bd
