### ISSUE TITLE
sizing parameters ignored upon cluster creation

### ISSUE THREAD

**Issue by sbesombes-CS** [CS-SI/SafeScale#149]
version: v21.11.0

When trying to create a cluster with the following command the sizing parameters seems to be ignored:

`safescale cluster create callisto --complexity=small --flavor=K8S --gw-sizing="template=d2-2" --master-sizing="template=b2-7" --node-sizing="template=b2-30"
`
Here is the result:
![image](https://user-images.githubusercontent.com/71491739/157283764-c45b62b7-95fb-44db-b903-99d039ffc921.png)

Here are the logs:
[cluster.log](https://github.com/CS-SI/SafeScale/files/8208038/cluster.log)

**Comment by oscarpicas** [comment]
Notice that the output of the command:

`safescale cluster create callisto --complexity=small --flavor=K8S --gw-sizing="template=d2-2" --master-sizing="template=b2-7" --node-sizing="template=b2-30"`

IS the expected one according to the docs.

This might seem surprising but it's not:
safescale uses urfave/cli/v2 to run the commands, this means that we MUST write flags before args:
https://github.com/urfave/cli/blob/master/docs/migrate-v1-to-v2.md#flags-before-args

So, what actually happens is that previous command actually is:
`safescale cluster create callisto`

because all the flags specified after `callisto` are IGNORED.

This would seem an invalid bug.... but running the fixed command:
`safescale cluster create --complexity=small --flavor=K8S --gw-sizing="template=d2-2" --master-sizing="template=b2-7" --node-sizing="template=b2-30" callisto`

creates the cluster, this time taking into account all the flags BUT some of the chosen templates are WRONG.

So, 1st thing is fix the template selection, then make explicit in the docs that choosing the wrong order results in ignored parameters and finally add warnings when we detect a command is 'obviously' wrong

**Comment by oscarpicas** [comment]
Much better (running command `safescale cluster create --complexity=small --flavor=K8S --gw-sizing="template=d2-2" --master-sizing="template=b2-7" --node-sizing="template=b2-30" callista`)

![image](https://user-images.githubusercontent.com/3659975/157658865-b0976e99-62d1-4fdb-8ee6-34d13cce6ddd.png)

**Comment by oscarpicas** [comment]
In order to test the fix, you should build the branch 'develop' or wait for next release. Assuming you have git, and docker in your machine, the fastest way to build is:
 
```
git clone https://github.com/CS-SI/SafeScale -depth 1 -b develop
cd SafeScale
./create-local-docker.sh
```
 
After that, you should see a ./exported directory, in there you should found the safescale and safescaled binaries
