### ISSUE TITLE
Improve error message when deleting a volume which is mounted

### ISSUE THREAD

**Issue by saimeCS** [CS-SI/SafeScale#4]
It is impossible to delete a volume if it is mounted on a VM: that's OK
Nevertheless, the error message is not clear to explain why the command doesn't succeded; use a message similar to: "Unable to delete volume 'volume_name' because it is mounted on VM 'VM_name'

**Comment by oscarpicas** [comment]
New message format after commit abe200b504840b4b766956140d2e7fca9ec92c01

Could not delete volume 'volumetest': rpc error: code = Unknown desc = **Unable to delete volume 'volumetest' because it's mounted on VM 'easyvm'**
Details: Error deleting volume: Bad request with: [DELETE https://volume.compute.sbg3.cloud.ovh.net/v1/........./volumes/.........], error message: {"badRequest": {"message": "Volume ........ is still attached, detach volume first.", "code": 400}}

We should think about adding a "verbose flag"

**Comment by oscarpicas** [comment]
Current message format:

Error response from daemon : **Cannot delete volume 'volumetest' because it's mounted on VM 'easyvm'**
Details: Error deleting volume: Bad request with: [DELETE https://volume.compute.sbg3.cloud.ovh.net/v1/....], error message: {"badRequest": {"message": "Volume ... is still attached, detach volume first.", "code": 400}}
